name: Test Core macOS
on: [workflow_dispatch]
jobs:
  test_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.2.0"
        pip install wheel build
        cd requirements
        pip install -r requirements.txt
        pip freeze
    - name: Install pyppbox from GitHub
      run: |
        pip install git+https://github.com/rathaumons/pyppbox.git
    - name: Install modules' data
      run: |
        pip install https://github.com/rathaumons/pyppbox-data/releases/download/v1.1.1/pyppbox_data_yolocls-1.1.1-py3-none-any.whl
        pip install https://github.com/rathaumons/pyppbox-data/releases/download/v1.1.1/pyppbox_data_yoloult-1.1.1-py3-none-any.whl
        pip install https://github.com/rathaumons/pyppbox-data/releases/download/v1.1.1/pyppbox_data_facenet-1.1.1-py3-none-any.whl
    - name: Prepare for tests
      run: |
        cd .githubtest
        python prepare_tests.py
    - name: Test 01 - Basic
      run: |
        cd .githubtest
        python test_01_basic.py
    - name: Test 02 (Skipped)
      run: |
        cd .githubtest
        # python test_02_eva_res.py
    - name: Test 03 - Evaluation Offline
      run: |
        cd .githubtest
        python test_03_eva_offline.py
    - name: Test 04 - Detector GT (Ground-truth)
      run: |
        cd .githubtest
        python test_04_dt_gt.py
    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: githubtest-results
        path: |
          .githubtest
